with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/vidconv/internal/inspector:
    interfaces:
      VideoProcessor:
  github.com/clambin/vidconv/internal/processor:
    interfaces:
      VideoConvertor:
