name: Test

on:
  push:
#   branches-ignore:
#     - main
#     - workflows
  pull_request_target:

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go122
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}